repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check --fix
        language: system
        types: [python]
        files: ^(pve_server|tests)/
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: system
        types: [python]
        files: ^(pve_server|tests)/
      - id: black
        name: black
        entry: uv run black
        language: system
        types: [python]
        files: ^(pve_server|tests)/
      - id: mypy
        name: mypy
        entry: uv run mypy pve_server/
        language: system
        types: [python]
        pass_filenames: false
